import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import 'package:kiamis_app/presentation/add_reared_livestock_dialog_one_dialog/models/add_reared_livestock_dialog_one_model.dart';part 'add_reared_livestock_dialog_one_event.dart';part 'add_reared_livestock_dialog_one_state.dart';/// A bloc that manages the state of a AddRearedLivestockDialogOne according to the event that is dispatched to it.
class AddRearedLivestockDialogOneBloc extends Bloc<AddRearedLivestockDialogOneEvent, AddRearedLivestockDialogOneState> {AddRearedLivestockDialogOneBloc(AddRearedLivestockDialogOneState initialState) : super(initialState) { on<AddRearedLivestockDialogOneInitialEvent>(_onInitialize); on<ChangeCheckBoxEvent>(_changeCheckBox); on<ChangeCheckBox1Event>(_changeCheckBox1); on<ChangeCheckBox2Event>(_changeCheckBox2); on<ChangeCheckBox3Event>(_changeCheckBox3); on<ChangeCheckBox4Event>(_changeCheckBox4); on<ChangeCheckBox5Event>(_changeCheckBox5); on<ChangeCheckBox6Event>(_changeCheckBox6); on<ChangeCheckBox7Event>(_changeCheckBox7); on<ChangeCheckBox8Event>(_changeCheckBox8); on<ChangeCheckBox9Event>(_changeCheckBox9); }

_changeCheckBox(ChangeCheckBoxEvent event, Emitter<AddRearedLivestockDialogOneState> emit, ) { emit(state.copyWith(calfPellets: event.value)); } 
_changeCheckBox1(ChangeCheckBox1Event event, Emitter<AddRearedLivestockDialogOneState> emit, ) { emit(state.copyWith(chickMarsh: event.value)); } 
_changeCheckBox2(ChangeCheckBox2Event event, Emitter<AddRearedLivestockDialogOneState> emit, ) { emit(state.copyWith(homeMadeFeedMix: event.value)); } 
_changeCheckBox3(ChangeCheckBox3Event event, Emitter<AddRearedLivestockDialogOneState> emit, ) { emit(state.copyWith(improvedPasture: event.value)); } 
_changeCheckBox4(ChangeCheckBox4Event event, Emitter<AddRearedLivestockDialogOneState> emit, ) { emit(state.copyWith(manufacturedMea: event.value)); } 
_changeCheckBox5(ChangeCheckBox5Event event, Emitter<AddRearedLivestockDialogOneState> emit, ) { emit(state.copyWith(mineralSalts: event.value)); } 
_changeCheckBox6(ChangeCheckBox6Event event, Emitter<AddRearedLivestockDialogOneState> emit, ) { emit(state.copyWith(ownGrownHay: event.value)); } 
_changeCheckBox7(ChangeCheckBox7Event event, Emitter<AddRearedLivestockDialogOneState> emit, ) { emit(state.copyWith(trash: event.value)); } 
_changeCheckBox8(ChangeCheckBox8Event event, Emitter<AddRearedLivestockDialogOneState> emit, ) { emit(state.copyWith(purchasedFodder: event.value)); } 
_changeCheckBox9(ChangeCheckBox9Event event, Emitter<AddRearedLivestockDialogOneState> emit, ) { emit(state.copyWith(purchasedHay: event.value)); } 
_onInitialize(AddRearedLivestockDialogOneInitialEvent event, Emitter<AddRearedLivestockDialogOneState> emit, ) async  { emit(state.copyWith(calfPellets: false, chickMarsh: false, homeMadeFeedMix: false, improvedPasture: false, manufacturedMea: false, mineralSalts: false, ownGrownHay: false, trash: false, purchasedFodder: false, purchasedHay: false)); } 
 }
