import 'bloc/transfer_amount_bloc.dart';import 'models/transfer_amount_model.dart';import 'package:flutter/material.dart';import 'package:kiamis_app/core/app_export.dart';import 'package:kiamis_app/widgets/app_bar/appbar_iconbutton.dart';import 'package:kiamis_app/widgets/app_bar/appbar_subtitle_2.dart';import 'package:kiamis_app/widgets/app_bar/custom_app_bar.dart';import 'package:kiamis_app/widgets/custom_elevated_button.dart';class TransferAmountScreen extends StatelessWidget {const TransferAmountScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<TransferAmountBloc>(create: (context) => TransferAmountBloc(TransferAmountState(transferAmountModelObj: TransferAmountModel()))..add(TransferAmountInitialEvent()), child: TransferAmountScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<TransferAmountBloc, TransferAmountState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 49.v, leadingWidth: 59.h, leading: AppbarIconbutton(svgPath: ImageConstant.imgArrowleftBlack900, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v), onTap: () {onTapArrowleftone(context);}), centerTitle: true, title: AppbarSubtitle2(text: "lbl_transfer_amount".tr)), body: SizedBox(width: double.maxFinite, child: Column(children: [Container(margin: EdgeInsets.only(left: 25.h, top: 25.v, right: 25.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 26.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Row(children: [Padding(padding: EdgeInsets.only(top: 10.v, bottom: 11.v), child: Text("lbl_to".tr, style: theme.textTheme.labelLarge)), CustomImageView(imagePath: ImageConstant.imgEllipse311, height: 40.adaptSize, width: 40.adaptSize, radius: BorderRadius.circular(20.h), margin: EdgeInsets.only(left: 14.h)), Padding(padding: EdgeInsets.only(left: 14.h, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_marlee_rice".tr, style: CustomTextStyles.titleSmallBlack900), Text("lbl_id_14345112075".tr, style: CustomTextStyles.labelMediumGray500)]))]), SizedBox(height: 23.v), Divider(color: appTheme.gray200), SizedBox(height: 13.v), Text("lbl_amount".tr, style: theme.textTheme.labelLarge), SizedBox(height: 5.v), Align(alignment: Alignment.center, child: Text("lbl_0".tr, style: CustomTextStyles.headlineLargeBlack900)), SizedBox(height: 8.v), Align(alignment: Alignment.center, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_available_balance2".tr, style: CustomTextStyles.bodySmallGray500), TextSpan(text: " "), TextSpan(text: "lbl_3_230_00".tr, style: CustomTextStyles.bodySmallIndigoA100)]), textAlign: TextAlign.left))])), Spacer()])), bottomNavigationBar: CustomElevatedButton(text: "lbl_send_money".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 34.v), buttonStyle: CustomButtonStyles.fillIndigoATL9, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700)));}); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleftone(BuildContext context) { NavigatorService.goBack(); } 
 }
