import 'bloc/profile_profile_info_tab_container_bloc.dart';import 'models/profile_profile_info_tab_container_model.dart';import 'package:flutter/material.dart';import 'package:kiamis_app/core/app_export.dart';import 'package:kiamis_app/presentation/profile_address_details_page/profile_address_details_page.dart';import 'package:kiamis_app/presentation/profile_my_orders_page/profile_my_orders_page.dart';import 'package:kiamis_app/presentation/profile_profile_info_page/profile_profile_info_page.dart';import 'package:kiamis_app/presentation/profile_security_page/profile_security_page.dart';import 'package:kiamis_app/widgets/app_bar/appbar_image.dart';import 'package:kiamis_app/widgets/app_bar/appbar_subtitle_3.dart';import 'package:kiamis_app/widgets/app_bar/custom_app_bar.dart';import 'package:kiamis_app/widgets/custom_icon_button.dart';class ProfileProfileInfoTabContainerScreen extends StatefulWidget {const ProfileProfileInfoTabContainerScreen({Key? key}) : super(key: key);

@override ProfileProfileInfoTabContainerScreenState createState() =>  ProfileProfileInfoTabContainerScreenState();
static Widget builder(BuildContext context) { return BlocProvider<ProfileProfileInfoTabContainerBloc>(create: (context) => ProfileProfileInfoTabContainerBloc(ProfileProfileInfoTabContainerState(profileProfileInfoTabContainerModelObj: ProfileProfileInfoTabContainerModel()))..add(ProfileProfileInfoTabContainerInitialEvent()), child: ProfileProfileInfoTabContainerScreen()); } 
 }

// ignore_for_file: must_be_immutable
class ProfileProfileInfoTabContainerScreenState extends State<ProfileProfileInfoTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 5, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<ProfileProfileInfoTabContainerBloc, ProfileProfileInfoTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 64.v, leadingWidth: 40.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftGray9000124x24, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowleftone(context);}), centerTitle: true, title: AppbarSubtitle3(text: "lbl_shopsie".tr), styleType: Style.bgFill), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Column(children: [Container(padding: EdgeInsets.symmetric(horizontal: 121.h, vertical: 32.v), decoration: AppDecoration.fillGray5002, child: Column(children: [SizedBox(height: 116.v, width: 100.h, child: Stack(alignment: Alignment.bottomLeft, children: [CustomImageView(imagePath: ImageConstant.imgProfileimage, height: 100.adaptSize, width: 100.adaptSize, radius: BorderRadius.circular(50.h), alignment: Alignment.topCenter), CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, margin: EdgeInsets.only(left: 31.h), padding: EdgeInsets.all(5.h), decoration: IconButtonStyleHelper.outlineBlack, alignment: Alignment.bottomLeft, child: CustomImageView(svgPath: ImageConstant.imgEdit2))])), SizedBox(height: 11.v), Text("lbl_archie_copeland".tr, style: CustomTextStyles.bodyLargeLatoGray90001), SizedBox(height: 12.v), Text("msg_allentown_new_mexico".tr, style: CustomTextStyles.bodyMediumGray6000114_1)])), SizedBox(height: 18.v), Container(height: 30.v, width: 390.h, child: TabBar(controller: tabviewController, isScrollable: true, labelColor: appTheme.indigoA200, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Lato', fontWeight: FontWeight.w400), unselectedLabelColor: appTheme.gray60001, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Lato', fontWeight: FontWeight.w400), indicatorColor: appTheme.indigoA200, tabs: [Tab(child: Text("lbl_profile_info".tr)), Tab(child: Text("lbl_my_orders".tr)), Tab(child: Text("lbl_security".tr)), Tab(child: Text("lbl_address_details".tr)), Tab(child: Text("lbl_log_out2".tr))])), SizedBox(height: 443.v, child: TabBarView(controller: tabviewController, children: [ProfileProfileInfoPage.builder(context), ProfileMyOrdersPage.builder(context), ProfileSecurityPage.builder(context), ProfileAddressDetailsPage.builder(context), ProfileAddressDetailsPage.builder(context)]))])))));}); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleftone(BuildContext context) { NavigatorService.goBack(); } 
 }
