import '../product_page_screen/widgets/slider_item_widget.dart';import 'bloc/product_page_bloc.dart';import 'models/product_page_model.dart';import 'models/slider_item_model.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:kiamis_app/core/app_export.dart';import 'package:kiamis_app/widgets/app_bar/appbar_image.dart';import 'package:kiamis_app/widgets/app_bar/appbar_subtitle_3.dart';import 'package:kiamis_app/widgets/app_bar/custom_app_bar.dart';import 'package:kiamis_app/widgets/custom_elevated_button.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class ProductPageScreen extends StatelessWidget {const ProductPageScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ProductPageBloc>(create: (context) => ProductPageBloc(ProductPageState(productPageModelObj: ProductPageModel()))..add(ProductPageInitialEvent()), child: ProductPageScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 56.v, leadingWidth: 40.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftGray90001, margin: EdgeInsets.only(left: 16.h, top: 12.v, bottom: 21.v), onTap: () {onTapArrowleftone(context);}), centerTitle: true, title: AppbarSubtitle3(text: "lbl_shopsie".tr)), body: Container(width: 390.h, padding: EdgeInsets.symmetric(vertical: 1.v), child: Column(children: [SizedBox(height: 6.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [BlocBuilder<ProductPageBloc, ProductPageState>(builder: (context, state) {return CarouselSlider.builder(options: CarouselOptions(height: 289.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {state.sliderIndex = index;}), itemCount: state.productPageModelObj?.sliderItemList.length ?? 0, itemBuilder: (context, index, realIndex) {SliderItemModel model = state.productPageModelObj?.sliderItemList[index] ?? SliderItemModel(); return SliderItemWidget(model);});}), SizedBox(height: 21.v), Align(alignment: Alignment.center, child: BlocBuilder<ProductPageBloc, ProductPageState>(builder: (context, state) {return SizedBox(height: 4.v, child: AnimatedSmoothIndicator(activeIndex: state.sliderIndex, count: state.productPageModelObj?.sliderItemList.length ?? 0, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 4, activeDotColor: appTheme.indigoA200, dotColor: appTheme.gray60001, dotHeight: 4.v, dotWidth: 15.h)));})), Padding(padding: EdgeInsets.only(left: 20.h, top: 24.v), child: Text("msg_print_maxi_dress".tr, style: CustomTextStyles.headlineSmallLatoGray90001)), Padding(padding: EdgeInsets.only(left: 20.h, top: 15.v), child: Text("lbl_99_30".tr, style: CustomTextStyles.titleLargeLatoIndigoA200)), Padding(padding: EdgeInsets.only(left: 20.h, top: 28.v), child: Text("lbl_product_details".tr, style: CustomTextStyles.bodyMedium14)), Align(alignment: Alignment.center, child: Container(width: 356.h, margin: EdgeInsets.only(left: 20.h, top: 17.v, right: 13.h), child: Text("msg_mini_dress_with".tr, maxLines: 5, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumGray700.copyWith(height: 1.50))))]))))])), bottomNavigationBar: CustomElevatedButton(height: 48.v, text: "lbl_add_to_cart".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 64.v), buttonStyle: CustomButtonStyles.fillIndigoA, buttonTextStyle: CustomTextStyles.bodyMediumWhiteA700))); } 


/// Navigates to the previous screen.
///
/// This function takes a [BuildContext] object as a parameter, which is
/// used to build the navigation stack. When the action is triggered, this
/// function uses the [NavigatorService] to navigate to the previous screen
/// in the navigation stack.
onTapArrowleftone(BuildContext context) { NavigatorService.goBack(); } 
 }
