import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import 'package:kiamis_app/presentation/farmers_identification_two_screen/models/farmers_identification_two_model.dart';part 'farmers_identification_two_event.dart';part 'farmers_identification_two_state.dart';/// A bloc that manages the state of a FarmersIdentificationTwo according to the event that is dispatched to it.
class FarmersIdentificationTwoBloc extends Bloc<FarmersIdentificationTwoEvent, FarmersIdentificationTwoState> {FarmersIdentificationTwoBloc(FarmersIdentificationTwoState initialState) : super(initialState) { on<FarmersIdentificationTwoInitialEvent>(_onInitialize); on<ChangeDropDownEvent>(_changeDropDown); on<ChangeDropDown1Event>(_changeDropDown1); }

_changeDropDown(ChangeDropDownEvent event, Emitter<FarmersIdentificationTwoState> emit, ) { emit(state.copyWith(selectedDropDownValue: event.value)); } 
_changeDropDown1(ChangeDropDown1Event event, Emitter<FarmersIdentificationTwoState> emit, ) { emit(state.copyWith(selectedDropDownValue1: event.value)); } 
List<SelectionPopupModel> fillDropdownItemList() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
List<SelectionPopupModel> fillDropdownItemList1() { return [SelectionPopupModel(id: 1, title: "Item One", isSelected: true), SelectionPopupModel(id: 2, title: "Item Two"), SelectionPopupModel(id: 3, title: "Item Three")]; } 
_onInitialize(FarmersIdentificationTwoInitialEvent event, Emitter<FarmersIdentificationTwoState> emit, ) async  { emit(state.copyWith(idnumberoneController: TextEditingController(), mobileNumberController: TextEditingController(), emailController: TextEditingController(), addressController: TextEditingController())); emit(state.copyWith(farmersIdentificationTwoModelObj: state.farmersIdentificationTwoModelObj?.copyWith(dropdownItemList: fillDropdownItemList(), dropdownItemList1: fillDropdownItemList1()))); } 
 }
